#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif


// ── UART config ───────────────────────────────────────────────────────────────
#define IE_UART_NUM         UART_NUM_2
#define IE_UART_BAUD        921600
#define IE_UART_TX_PIN      17
#define IE_UART_RX_PIN      16

// ── Audio config ──────────────────────────────────────────────────────────────
#define IE_SAMPLE_RATE_HZ   16000

// Wakeword model window: verify EI_CLASSIFIER_RAW_SAMPLE_COUNT from
// components/ei_model/model-parameters/model_variables.h after unzipping
// the generated multi-impulse output. Update this value to match.
#define WW_WINDOW_SAMPLES   16000
#define WW_SLICE_SAMPLES    4000   // must match model_variables.h slice_size (16000/4)

// Command capture: 2 seconds of audio
#define CMD_CAPTURE_SAMPLES (IE_SAMPLE_RATE_HZ * 5)
#define CMD_MODEL_WINDOW_SAMPLES  16000  // must match impulse_1037438_3.dsp_input_frame_size

// ── Inference thresholds ──────────────────────────────────────────────────────
#define WW_CONFIDENCE_THRESHOLD  0.85f
#define CMD_CONFIDENCE_THRESHOLD 0.70f

// ── Impulse handle externs ────────────────────────────────────────────────────
// These names come from model_variables.h generated by the multi-impulse script.
// After unzipping, open model_variables.h and confirm the exact variable names
// for both ei_impulse_t declarations, then update these two lines.
#define WW_IMPULSE_HANDLE    impulse_1036490_1
#define CMD_IMPULSE_HANDLE   impulse_1037438_3


// ── Public API ────────────────────────────────────────────────────────────────
void inference_engine_init(void);


#ifdef __cplusplus
}
#endif